/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Miche
 */
public class Tareas_Pendientes extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    int contador = 0;

    /**
     * Creates new form Tareas_Pendientes
     */
    DefaultTableModel Tabla;

    public static ArrayList<Datos_Tarea> ArrayDatos;

    public Tareas_Pendientes() {
        initComponents();
        Cargar();
        CargarDatos();
        ArrayDatos = new ArrayList<Datos_Tarea>();
        Tabla = (DefaultTableModel) Tabla_Tareas_Pendientes.getModel();
        
        Tareas_Pendientes TP = new Tareas_Pendientes();
        TP.setVisible(true);
    }

    public void Mostrar_Segunda_Tabla() {
        
        modelo = new DefaultTableModel();
        Tabla_Tareas_Pendientes.setModel(modelo);
    }

    public void Cargar() {

        String datos[][] = {};
        String columna[] = {"Tarea", "Responsable", "Fecha"};

        modelo = new DefaultTableModel(datos, columna);
        Tabla_Tareas_Pendientes.setModel(modelo);

    }

    public void CargarDatos() {

        Datos_Tarea D = new Datos_Tarea();

        for (int i = 0; i < Programa_de_Tareas.ArrayDatos.size(); i++) {
            D = (Datos_Tarea) Programa_de_Tareas.ArrayDatos.get(i);
            modelo.insertRow(contador, new Object[]{});
            modelo.setValueAt(D.getTarea(), contador, 0);
            modelo.setValueAt(D.getResponsable(), contador, 1);
            modelo.setValueAt(D.getFecha(), contador, 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Tareas_Pendientes = new javax.swing.JTable();
        Txt_Nombre_Documento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Panel_Generar_Reporte = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Panel_Agregar_Tarea = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Panel_Finalizar_Tarea = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel_Finalizar_Todas_las_Tareas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 107, 173));
        jLabel1.setText("Tareas pendientes");

        Tabla_Tareas_Pendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Responsable de la tarea", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Tareas_Pendientes);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del documento:");

        Panel_Generar_Reporte.setBackground(new java.awt.Color(56, 107, 173));
        Panel_Generar_Reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Generar_Reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Generar_ReporteMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generar reporte - Tareas pendientes");

        javax.swing.GroupLayout Panel_Generar_ReporteLayout = new javax.swing.GroupLayout(Panel_Generar_Reporte);
        Panel_Generar_Reporte.setLayout(Panel_Generar_ReporteLayout);
        Panel_Generar_ReporteLayout.setHorizontalGroup(
            Panel_Generar_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Generar_ReporteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );
        Panel_Generar_ReporteLayout.setVerticalGroup(
            Panel_Generar_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Generar_ReporteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        Panel_Agregar_Tarea.setBackground(new java.awt.Color(56, 107, 173));
        Panel_Agregar_Tarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Agregar_Tarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Agregar_TareaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar nueva tarea");

        javax.swing.GroupLayout Panel_Agregar_TareaLayout = new javax.swing.GroupLayout(Panel_Agregar_Tarea);
        Panel_Agregar_Tarea.setLayout(Panel_Agregar_TareaLayout);
        Panel_Agregar_TareaLayout.setHorizontalGroup(
            Panel_Agregar_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Agregar_TareaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Panel_Agregar_TareaLayout.setVerticalGroup(
            Panel_Agregar_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Agregar_TareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Finalizar_Tarea.setBackground(new java.awt.Color(56, 107, 173));
        Panel_Finalizar_Tarea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Finalizar_Tarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Finalizar_TareaMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Finalizar tarea");

        javax.swing.GroupLayout Panel_Finalizar_TareaLayout = new javax.swing.GroupLayout(Panel_Finalizar_Tarea);
        Panel_Finalizar_Tarea.setLayout(Panel_Finalizar_TareaLayout);
        Panel_Finalizar_TareaLayout.setHorizontalGroup(
            Panel_Finalizar_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Finalizar_TareaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Panel_Finalizar_TareaLayout.setVerticalGroup(
            Panel_Finalizar_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Finalizar_TareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Finalizar_Todas_las_Tareas.setBackground(new java.awt.Color(56, 107, 173));
        Panel_Finalizar_Todas_las_Tareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Finalizar_Todas_las_Tareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Finalizar_Todas_las_TareasMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Finalizar todas las tareas");

        javax.swing.GroupLayout Panel_Finalizar_Todas_las_TareasLayout = new javax.swing.GroupLayout(Panel_Finalizar_Todas_las_Tareas);
        Panel_Finalizar_Todas_las_Tareas.setLayout(Panel_Finalizar_Todas_las_TareasLayout);
        Panel_Finalizar_Todas_las_TareasLayout.setHorizontalGroup(
            Panel_Finalizar_Todas_las_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Finalizar_Todas_las_TareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Finalizar_Todas_las_TareasLayout.setVerticalGroup(
            Panel_Finalizar_Todas_las_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Finalizar_Todas_las_TareasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Panel_Agregar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Txt_Nombre_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Panel_Generar_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(Panel_Finalizar_Todas_las_Tareas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Panel_Finalizar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Nombre_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Panel_Generar_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Panel_Finalizar_Todas_las_Tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Panel_Finalizar_Tarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(Panel_Agregar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_Generar_ReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Generar_ReporteMouseClicked

        Diseño_de_los_Reportes D = new Diseño_de_los_Reportes(Txt_Nombre_Documento.getText(), new Date().toString(), "C:\\Users\\Miche\\Downloads\\Reporte.png", Programa_de_Tareas.ArrayDatos);
        D.GenerarReporte_TareasPendientes();

    }//GEN-LAST:event_Panel_Generar_ReporteMouseClicked

    private void Panel_Agregar_TareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Agregar_TareaMouseClicked

        Programa_de_Tareas P = new Programa_de_Tareas();
        P.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Panel_Agregar_TareaMouseClicked

    private void Panel_Finalizar_TareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Finalizar_TareaMouseClicked

        int FilaSeleccionada = Tabla_Tareas_Pendientes.getSelectedRow();

        if (FilaSeleccionada >= 0) {

            String Datos[] = new String[3];

            Datos[0] = Tabla_Tareas_Pendientes.getValueAt(FilaSeleccionada, 0).toString();
            Datos[1] = Tabla_Tareas_Pendientes.getValueAt(FilaSeleccionada, 1).toString();
            Datos[2] = Tabla_Tareas_Pendientes.getValueAt(FilaSeleccionada, 2).toString();

            Tareas_Finalizadas.modelo2.addRow(Datos);
            modelo.removeRow(FilaSeleccionada);

        }

    }//GEN-LAST:event_Panel_Finalizar_TareaMouseClicked

    private void Panel_Finalizar_Todas_las_TareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Finalizar_Todas_las_TareasMouseClicked

        for (int i = 0; i < Tabla_Tareas_Pendientes.getRowCount(); i++) {

            String Datos[] = new String[3];

            Datos[0] = Tabla_Tareas_Pendientes.getValueAt(i, 0).toString();
            Datos[1] = Tabla_Tareas_Pendientes.getValueAt(i, 1).toString();
            Datos[2] = Tabla_Tareas_Pendientes.getValueAt(i, 2).toString();

            Tareas_Finalizadas.modelo2.addRow(Datos);

        }

        Mostrar_Segunda_Tabla();

    }//GEN-LAST:event_Panel_Finalizar_Todas_las_TareasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tareas_Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tareas_Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tareas_Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tareas_Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Tareas_Pendientes().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Agregar_Tarea;
    private javax.swing.JPanel Panel_Finalizar_Tarea;
    private javax.swing.JPanel Panel_Finalizar_Todas_las_Tareas;
    private javax.swing.JPanel Panel_Generar_Reporte;
    public static javax.swing.JTable Tabla_Tareas_Pendientes;
    private javax.swing.JTextField Txt_Nombre_Documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
